[package]
name = "core-api"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["fs", "process", "rt-multi-thread"] }
serde = { version = "1.0", features = [] }
serde_json = "1.0"
reqwest = { version = "0.11.16", features = ["gzip"] }
regex = "1.6.0"
